/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Schemas */
        get: operations["list_schemas_api_v1_schemas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_agent_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Message */
        post: operations["post_message_api_v1_agent_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/sessions/{session_id}/task-spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bind Task Spec */
        post: operations["bind_task_spec_api_v1_agent_sessions__session_id__task_spec_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/sessions/{session_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Plan */
        post: operations["submit_plan_api_v1_agent_sessions__session_id__plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/sessions/{session_id}/plan/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Plan */
        post: operations["approve_plan_api_v1_agent_sessions__session_id__plan_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_agent_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/sessions/{session_id}/actions/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Session */
        post: operations["pause_session_api_v1_agent_sessions__session_id__actions_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Events
         * @description 行动事件流：SSE（默认）或 JSON（format=json，供测试/降级）。
         */
        get: operations["session_events_api_v1_agent_sessions__session_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/actions/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Task */
        post: operations["resume_task_api_v1_tasks__task_id__actions_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/actions/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Task */
        post: operations["cancel_task_api_v1_tasks__task_id__actions_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Claims */
        get: operations["list_claims_api_v1_claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{claim_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Claim Evidence */
        get: operations["get_claim_evidence_api_v1_claims__claim_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verification/aggregations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verification Aggregations */
        get: operations["verification_aggregations_api_v1_verification_aggregations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/sessions/{session_id}/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Coverage */
        get: operations["session_coverage_api_v1_agent_sessions__session_id__coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Queue */
        get: operations["review_queue_api_v1_reviews_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Review Decision */
        post: operations["submit_review_decision_api_v1_reviews_decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionResponse */
        ActionResponse: {
            /** Id */
            id: string;
            /** Turn */
            turn: number;
            /** Action Type */
            action_type: string;
            /** Tool Name */
            tool_name?: string | null;
            /** Status */
            status: string;
            /**
             * Result Summary
             * @default
             */
            result_summary: string;
            /** Created At */
            created_at: string;
        };
        /** AgentEventItem */
        AgentEventItem: {
            /** Seq */
            seq: number;
            /** Turn */
            turn: number;
            /** Action Type */
            action_type: string;
            /** Tool Name */
            tool_name?: string | null;
            /** Status */
            status: string;
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /** AggregationItem */
        AggregationItem: {
            /** Claim Id */
            claim_id: string;
            /** Canonical Signature */
            canonical_signature: string;
            /** Status */
            status: string;
            /**
             * Support Count
             * @default 0
             */
            support_count: number;
            /**
             * Contradict Count
             * @default 0
             */
            contradict_count: number;
            /**
             * No Effect Count
             * @default 0
             */
            no_effect_count: number;
            /**
             * Uncertain Count
             * @default 0
             */
            uncertain_count: number;
            /**
             * Independent Validation
             * @default false
             */
            independent_validation: boolean;
            /**
             * Has Conflict
             * @default false
             */
            has_conflict: boolean;
            /**
             * Needs Review
             * @default false
             */
            needs_review: boolean;
            /**
             * Distinct Documents
             * @default 0
             */
            distinct_documents: number;
            /** Reasons */
            reasons?: string[];
        };
        /** AggregationsResponse */
        AggregationsResponse: {
            /** Aggregations */
            aggregations?: components["schemas"]["AggregationItem"][];
        };
        /** ApprovePlanRequest */
        ApprovePlanRequest: {
            /** Plan Version */
            plan_version: number;
        };
        /** BindTaskSpecRequest */
        BindTaskSpecRequest: {
            /** Disease */
            disease?: string | null;
            /** Task */
            task?: string | null;
            /** Validation Requirement */
            validation_requirement?: string | null;
            /** Year From */
            year_from?: number | null;
            /** Year To */
            year_to?: number | null;
            /** Publication Types */
            publication_types?: string[];
        };
        /** ClaimEvidenceItem */
        ClaimEvidenceItem: {
            /** Evidence Id */
            evidence_id: string;
            /** Polarity */
            polarity: string;
            span: components["schemas"]["ClaimEvidenceSpan"];
            /** Study */
            study?: {
                [key: string]: unknown;
            };
            /** Statistics */
            statistics?: {
                [key: string]: unknown;
            } | null;
            /**
             * Review Status
             * @default pending
             */
            review_status: string;
            /**
             * Document Version Id
             * @default
             */
            document_version_id: string;
            /**
             * Document Title
             * @default
             */
            document_title: string;
            /**
             * Canonical Text
             * @description span 所在的固定 canonical text，用于 UI 高亮定位
             * @default
             */
            canonical_text: string;
        };
        /** ClaimEvidenceResponse */
        ClaimEvidenceResponse: {
            /** Claim Id */
            claim_id: string;
            /** Canonical Signature */
            canonical_signature: string;
            /** Evidence */
            evidence?: components["schemas"]["ClaimEvidenceItem"][];
        };
        /** ClaimEvidenceSpan */
        ClaimEvidenceSpan: {
            /** Document Version Id */
            document_version_id: string;
            /** Passage Id */
            passage_id: string;
            /**
             * Section Path
             * @default
             */
            section_path: string;
            /** Start Char */
            start_char: number;
            /** End Char */
            end_char: number;
            /** Text */
            text: string;
        };
        /** ClaimResponse */
        ClaimResponse: {
            /** Claim Id */
            claim_id: string;
            /** Canonical Signature */
            canonical_signature: string;
            /** Status */
            status: string;
            /** Predicate */
            predicate: string;
            /** Direction */
            direction: string;
            /**
             * Evidence Count
             * @default 0
             */
            evidence_count: number;
            /** Polarities */
            polarities?: {
                [key: string]: number;
            };
        };
        /** ClaimsResponse */
        ClaimsResponse: {
            /** Claims */
            claims?: components["schemas"]["ClaimResponse"][];
        };
        /** CoverageQuestionItem */
        CoverageQuestionItem: {
            /** Question */
            question: string;
            /**
             * Support Count
             * @default 0
             */
            support_count: number;
            /**
             * Contradict Count
             * @default 0
             */
            contradict_count: number;
            /**
             * No Effect Count
             * @default 0
             */
            no_effect_count: number;
            /**
             * Uncertain Count
             * @default 0
             */
            uncertain_count: number;
            /**
             * Independent Validation Found
             * @default false
             */
            independent_validation_found: boolean;
            /**
             * Covered
             * @default false
             */
            covered: boolean;
        };
        /** CoverageResponse */
        CoverageResponse: {
            /** Session Id */
            session_id: string;
            /** Questions */
            questions?: components["schemas"]["CoverageQuestionItem"][];
            /**
             * Support Count
             * @default 0
             */
            support_count: number;
            /**
             * Contradict Count
             * @default 0
             */
            contradict_count: number;
            /**
             * No Effect Count
             * @default 0
             */
            no_effect_count: number;
            /**
             * Independent Validation Found
             * @default false
             */
            independent_validation_found: boolean;
            /** Unresolved Gaps */
            unresolved_gaps?: string[];
            /** Recommended Next Action */
            recommended_next_action?: string | null;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /**
             * Goal
             * @description 自然语言研究目标
             */
            goal: string;
            /**
             * User Id
             * @default anonymous
             */
            user_id: string;
            /** Limits */
            limits?: {
                [key: string]: unknown;
            };
        };
        /** CreateSessionResponse */
        CreateSessionResponse: {
            /** Session Id */
            session_id: string;
            /** Status */
            status: string;
            /** Next */
            next: string;
        };
        /** CreateTaskRequest */
        CreateTaskRequest: {
            /** Session Id */
            session_id?: string | null;
            /** Intents */
            intents?: {
                [key: string]: unknown;
            }[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PlanResponse */
        PlanResponse: {
            /** Version */
            version: number;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Steps */
            steps?: components["schemas"]["PlanStepResponse"][];
            /**
             * Approved By Human
             * @default false
             */
            approved_by_human: boolean;
        };
        /** PlanStepResponse */
        PlanStepResponse: {
            /** Id */
            id: string;
            /** Action Type */
            action_type: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Search Intent */
            search_intent?: string | null;
            /**
             * Status
             * @default pending
             */
            status: string;
        };
        /** PostMessageRequest */
        PostMessageRequest: {
            /**
             * Role
             * @description user | agent | system
             * @default user
             */
            role: string;
            /** Content */
            content: string;
            /**
             * Kind
             * @default text
             */
            kind: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /** ReviewDecisionRequest */
        ReviewDecisionRequest: {
            /** Claim Id */
            claim_id: string;
            /**
             * Decision
             * @description ACCEPT | EDIT_ACCEPT | REJECT | NEEDS_REVIEW
             */
            decision: string;
            /** Reviewer Id */
            reviewer_id: string;
            /** Reason */
            reason: string;
            /**
             * Expected Version
             * @description 乐观锁：审核者看到的 claim 版本
             */
            expected_version: number;
            /**
             * Revision
             * @description EDIT_ACCEPT 的修订字段
             */
            revision?: {
                [key: string]: unknown;
            };
        };
        /** ReviewDecisionResponse */
        ReviewDecisionResponse: {
            /** Ok */
            ok: boolean;
            /** Claim Status */
            claim_status: string;
            /** Claim Version */
            claim_version: number;
            /** Review Id */
            review_id: string;
        };
        /** ReviewQueueItem */
        ReviewQueueItem: {
            /** Claim Id */
            claim_id: string;
            /** Canonical Signature */
            canonical_signature: string;
            /** Status */
            status: string;
            /** Priority */
            priority: string;
            /** Reasons */
            reasons?: string[];
            /**
             * Evidence Count
             * @default 0
             */
            evidence_count: number;
            /** Polarities */
            polarities?: {
                [key: string]: number;
            };
        };
        /** ReviewQueueResponse */
        ReviewQueueResponse: {
            /** Items */
            items?: components["schemas"]["ReviewQueueItem"][];
        };
        /** SessionEventsResponse */
        SessionEventsResponse: {
            /** Events */
            events?: components["schemas"]["AgentEventItem"][];
            /**
             * Next Since
             * @default 0
             */
            next_since: number;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Session Id */
            session_id: string;
            /** Goal */
            goal: string;
            /** Status */
            status: string;
            task_spec?: components["schemas"]["TaskSpecResponse"] | null;
            /** Plans */
            plans?: components["schemas"]["PlanResponse"][];
            /**
             * Current Plan Version
             * @default 0
             */
            current_plan_version: number;
            /** Budget */
            budget?: {
                [key: string]: unknown;
            };
            /** Budget State */
            budget_state?: {
                [key: string]: unknown;
            };
            /** Stop Reason */
            stop_reason?: {
                [key: string]: unknown;
            } | null;
            /** Actions */
            actions?: components["schemas"]["ActionResponse"][];
            /**
             * Turn
             * @default 0
             */
            turn: number;
        };
        /** SubmitPlanRequest */
        SubmitPlanRequest: {
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Steps */
            steps?: components["schemas"]["PlanStepResponse"][];
        };
        /** TaskResponse */
        TaskResponse: {
            /** Task Id */
            task_id: string;
            /** Session Id */
            session_id?: string | null;
            /** Status */
            status: string;
            /** Steps */
            steps?: components["schemas"]["TaskStepResponse"][];
        };
        /** TaskSpecResponse */
        TaskSpecResponse: {
            /** Schema Name */
            schema_name: string;
            /** Schema Version */
            schema_version: string;
            /** Disease */
            disease?: string | null;
            /** Task */
            task?: string | null;
            /** Validation Requirement */
            validation_requirement?: string | null;
            /** Year From */
            year_from?: number | null;
            /** Year To */
            year_to?: number | null;
            /** Missing Required Fields */
            missing_required_fields?: string[];
        };
        /** TaskStepResponse */
        TaskStepResponse: {
            /** Index */
            index: number;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_schemas_api_v1_schemas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_session_api_v1_agent_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_api_v1_agent_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_task_spec_api_v1_agent_sessions__session_id__task_spec_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindTaskSpecRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_plan_api_v1_agent_sessions__session_id__plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_plan_api_v1_agent_sessions__session_id__plan_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovePlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_agent_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_session_api_v1_agent_sessions__session_id__actions_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_events_api_v1_agent_sessions__session_id__events_get: {
        parameters: {
            query?: {
                since?: number;
                format?: string;
                max_events?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_task_api_v1_tasks__task_id__actions_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_task_api_v1_tasks__task_id__actions_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_claims_api_v1_claims_get: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_claim_evidence_api_v1_claims__claim_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimEvidenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verification_aggregations_api_v1_verification_aggregations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_coverage_api_v1_agent_sessions__session_id__coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_queue_api_v1_reviews_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueResponse"];
                };
            };
        };
    };
    submit_review_decision_api_v1_reviews_decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
